// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey:
        dotenv.maybeGet('WEB_AND_WINDOWS_FIREBASE_API_KEY') ??
        const String.fromEnvironment(
          'WEB_AND_WINDOWS_FIREBASE_API_KEY',
          defaultValue: '',
        ),
    appId:
        dotenv.maybeGet('WEB_APPID') ??
        const String.fromEnvironment('WEB_APPID', defaultValue: ''),
    messagingSenderId:
        dotenv.maybeGet('MESSAGING_SENDER_ID') ??
        const String.fromEnvironment('MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey:
        dotenv.maybeGet('ANDROID_FIREBASE_API_KEY') ??
        const String.fromEnvironment(
          'ANDROID_FIREBASE_API_KEY',
          defaultValue: '',
        ),
    appId:
        dotenv.maybeGet('ANDROID_APPID') ??
        const String.fromEnvironment('ANDROID_APPID', defaultValue: ''),
    messagingSenderId:
        dotenv.maybeGet('MESSAGING_SENDER_ID') ??
        const String.fromEnvironment('MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey:
        dotenv.maybeGet('IOS_AND_MACOS_FIREBASE_API_KEY') ??
        const String.fromEnvironment(
          'IOS_AND_MACOS_FIREBASE_API_KEY',
          defaultValue: '',
        ),
    appId:
        dotenv.maybeGet('IOS_MACOS_APPID') ??
        const String.fromEnvironment('IOS_MACOS_APPID', defaultValue: ''),
    messagingSenderId:
        dotenv.maybeGet('MESSAGING_SENDER_ID') ??
        const String.fromEnvironment('MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey:
        dotenv.maybeGet('IOS_AND_MACOS_FIREBASE_API_KEY') ??
        const String.fromEnvironment(
          'IOS_AND_MACOS_FIREBASE_API_KEY',
          defaultValue: '',
        ),
    appId:
        dotenv.maybeGet('IOS_MACOS_APPID') ??
        const String.fromEnvironment('IOS_MACOS_APPID', defaultValue: ''),
    messagingSenderId:
        dotenv.maybeGet('MESSAGING_SENDER_ID') ??
        const String.fromEnvironment('MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey:
        dotenv.maybeGet('WEB_AND_WINDOWS_FIREBASE_API_KEY') ??
        const String.fromEnvironment(
          'WEB_AND_WINDOWS_FIREBASE_API_KEY',
          defaultValue: '',
        ),
    appId:
        dotenv.maybeGet('WINDOWS_APPID') ??
        const String.fromEnvironment('WINDOWS_APPID', defaultValue: ''),
    messagingSenderId:
        dotenv.maybeGet('MESSAGING_SENDER_ID') ??
        const String.fromEnvironment('MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );
}
