// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kReleaseMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Define const values from dart-define
  static const String _webApiKey = String.fromEnvironment(
    'WEB_AND_WINDOWS_FIREBASE_API_KEY',
  );
  static const String _webAppId = String.fromEnvironment('WEB_APPID');
  static const String _androidApiKey = String.fromEnvironment(
    'ANDROID_FIREBASE_API_KEY',
  );
  static const String _androidAppId = String.fromEnvironment('ANDROID_APPID');
  static const String _iosApiKey = String.fromEnvironment(
    'IOS_AND_MACOS_FIREBASE_API_KEY',
  );
  static const String _iosAppId = String.fromEnvironment('IOS_MACOS_APPID');
  static const String _windowsAppId = String.fromEnvironment('WINDOWS_APPID');
  static const String _messagingSenderId = String.fromEnvironment(
    'MESSAGING_SENDER_ID',
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: kReleaseMode
        ? _webApiKey
        : (dotenv.env['WEB_AND_WINDOWS_FIREBASE_API_KEY'] ?? ''),
    appId: kReleaseMode ? _webAppId : (dotenv.env['WEB_APPID'] ?? ''),
    messagingSenderId: kReleaseMode
        ? _messagingSenderId
        : (dotenv.env['MESSAGING_SENDER_ID'] ?? ''),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: kReleaseMode
        ? _androidApiKey
        : (dotenv.env['ANDROID_FIREBASE_API_KEY'] ?? ''),
    appId: kReleaseMode ? _androidAppId : (dotenv.env['ANDROID_APPID'] ?? ''),
    messagingSenderId: kReleaseMode
        ? _messagingSenderId
        : (dotenv.env['MESSAGING_SENDER_ID'] ?? ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: kReleaseMode
        ? _iosApiKey
        : (dotenv.env['IOS_AND_MACOS_FIREBASE_API_KEY'] ?? ''),
    appId: kReleaseMode ? _iosAppId : (dotenv.env['IOS_MACOS_APPID'] ?? ''),
    messagingSenderId: kReleaseMode
        ? _messagingSenderId
        : (dotenv.env['MESSAGING_SENDER_ID'] ?? ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: kReleaseMode
        ? _iosApiKey
        : (dotenv.env['IOS_AND_MACOS_FIREBASE_API_KEY'] ?? ''),
    appId: kReleaseMode ? _iosAppId : (dotenv.env['IOS_MACOS_APPID'] ?? ''),
    messagingSenderId: kReleaseMode
        ? _messagingSenderId
        : (dotenv.env['MESSAGING_SENDER_ID'] ?? ''),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: kReleaseMode
        ? _webApiKey
        : (dotenv.env['WEB_AND_WINDOWS_FIREBASE_API_KEY'] ?? ''),
    appId: kReleaseMode ? _windowsAppId : (dotenv.env['WINDOWS_APPID'] ?? ''),
    messagingSenderId: kReleaseMode
        ? _messagingSenderId
        : (dotenv.env['MESSAGING_SENDER_ID'] ?? ''),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );
}
