// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kReleaseMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getConfig('WEB_AND_WINDOWS_FIREBASE_API_KEY'),
    appId: _getConfig('WEB_APPID'),
    messagingSenderId: _getConfig('MESSAGING_SENDER_ID'),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _getConfig('ANDROID_FIREBASE_API_KEY'),
    appId: _getConfig('ANDROID_APPID'),
    messagingSenderId: _getConfig('MESSAGING_SENDER_ID'),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getConfig('IOS_AND_MACOS_FIREBASE_API_KEY'),
    appId: _getConfig('IOS_MACOS_APPID'),
    messagingSenderId: _getConfig('MESSAGING_SENDER_ID'),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _getConfig('IOS_AND_MACOS_FIREBASE_API_KEY'),
    appId: _getConfig('IOS_MACOS_APPID'),
    messagingSenderId: _getConfig('MESSAGING_SENDER_ID'),
    projectId: 'netlab-8c22e',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
    iosBundleId: 'com.example.netlab',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _getConfig('WEB_AND_WINDOWS_FIREBASE_API_KEY'),
    appId: _getConfig('WINDOWS_APPID'),
    messagingSenderId: _getConfig('MESSAGING_SENDER_ID'),
    projectId: 'netlab-8c22e',
    authDomain: 'netlab-8c22e.firebaseapp.com',
    storageBucket: 'netlab-8c22e.firebasestorage.app',
  );

  /// Helper method to get config values from either .env (debug) or dart-define (release)
  static String _getConfig(String key) {
    if (kReleaseMode) {
      // In production/release mode, use dart-define values
      return String.fromEnvironment(key, defaultValue: '');
    }
    // In debug mode, use .env file
    return dotenv.env[key] ?? '';
  }
}
